### ISSUE TITLE
[FEAT] 개발 환경 세팅 및 배포

### ISSUE THREAD

**Issue by GoodDonkey** [recody-project/recody-backend#3]
**Description**  
개발환경 세팅 

**Todos**  
- [ ] 데이터베이스 rds, mysql 
- [x] CI/CD beanstalk 로 일단 하기(가능하면 ecs 로 알아보기)
- [ ] 배포 주소 프론트와 공유
