### ISSUE TITLE
[FEAT] 카프카 세팅 

### ISSUE THREAD

**Issue by GoodDonkey** [recody-project/recody-backend#4]
**Description**  
카프카 세팅. 알아볼게 많음. 

**Todos**  
- [ ] 토픽을 어떻게 관리할 것인가?
- [ ] 배포는 어떻게 할 것인가?
- [ ] 최소한의 코드로 컨슈머들을 관리하기 위한 전략?
- [ ] 자바 코드로 대부분 자동 세팅을 시키고, 직접 명령을 할 수도 있는 상황 대비.
